### ISSUE TITLE
Improve tests to actually use zookeeper and solr back-end

### ISSUE THREAD

**Issue by rfay** [mkalkbrenner/ddev-solr#13]
One detail is we should beef up the tests a bit to actually use zookeeper and the solr back-end just a bit. Right now it only checks to see if the Solr UI is functioning, which isn't a real thing. 

Best situation:
* Install Drupal 10 with search_api_solr_admin
* Do the drush to set up if possible
* Do something to prove it works. 

It isn't necessary to do this before the promotion of this project to ddev org, but it will definitely make the tests more robust.

**Comment by mkalkbrenner** [comment]
Actually the solr start command already uploads security.json to zookeeper.

But I agree, that some more tests would be fine.

**Comment by mkalkbrenner** [comment]
@rfay I can't get the tests to work. I don't find the the testdata directory. Could you take a look?

**Comment by rfay** [comment]
Happy to take a look, but would you mind rolling back to the working version and doing a PR with the new stuff? 

https://github.com/mkalkbrenner/ddev-solr/commit/6b62fe72ede8cdb10cf9af7a4bb8a2340557355c was working, you can revert to it and then make a PR for what you're trying to do with the tests (or other things?). Then I'd be able to look at it more clearly.

I'm happy to do a debugging session with you as well, we could do a screenshare on discord. If you have time in the next 2 hours and could get the PR set up we can do this afternoon your time, or we could do it tomorrow afternoon your time.

**Comment by mkalkbrenner** [comment]
@rfay I created #18 

The problem is that https://github.com/mkalkbrenner/ddev-solr/blob/upload_test/tests/testdata/techproducts_configset.zip could not be loaded within the test.

**Comment by mkalkbrenner** [comment]
@rfay any idea what needs to br done to access https://github.com/mkalkbrenner/ddev-solr/blob/upload_test/tests/testdata/techproducts_configset.zip within the tests?

**Comment by rfay** [comment]
Will see if I can take a look now that we got ddev v1.22.0-beta1 out. Thanks for your work on this!

**Comment by rfay** [comment]
* https://github.com/mkalkbrenner/ddev-solr/pull/19

**Comment by mkalkbrenner** [comment]
@rfay thanks for your help. It works now 👍

**Comment by rfay** [comment]
Yay!
