### ISSUE TITLE
README suggestions

### ISSUE THREAD

**Issue by rfay** [mkalkbrenner/ddev-solr#2]
Some suggestions for readme:

- [ ] Add that it's supported for both amd64 and arm64 (Apple Silicon)
- [ ]

**Comment by mkalkbrenner** [comment]
@rfay I can't test Apple Silicon.

**Comment by rfay** [comment]
I understand, I think it's fine to say it's supported; worked for me just fine on mac M1. We could do automated tests on M1 but I think it's more effort than required. 

I'll close this and we can just not say anything about arm64. It works anyway.
