### ISSUE TITLE
Consider using official zookeeper image

### ISSUE THREAD

**Issue by rfay** [mkalkbrenner/ddev-solr#3]
The official zookeeper image now has arm64 images, https://hub.docker.com/_/zookeeper/tags

Please consider using `zookeeper: 3.8` if you're happy with it.

**Comment by mkalkbrenner** [comment]
We had an issue with the official zookeeper image and volumes, maybe two years ago. But I'll try again.

**Comment by mkalkbrenner** [comment]
@rfay I remember the issue now. The official zookeper image stores the data in two top level directories `/data` and `/datalog`, wheras the bitnami image stores everything under `/bitnami/zookeeper`.

As you probably remember we had issues in DDEV if two volumes were required. Are these solved?

**Comment by rfay** [comment]
You're right, good memory. I think DDEV can probably do it now, but I don't think it's worth messing with.
