### ISSUE TITLE
How do you Upload (and overwrite) configset?

### ISSUE THREAD

**Issue by rfay** [mkalkbrenner/ddev-solr#4]
When I got to the step:

> Press the Upload Configset button on the server's view and check the "Upload (and overwrite) configset" checkbox.

I was unable to find any checkbox of that type, so was stuck there. What should I have done? 

Using search_api_solr 4.2.10

**Comment by mkalkbrenner** [comment]
Probably you did step 1 wrong and just enabled `search_api_solr` instead of the `search_api_solr_admin` module?
(`search_api_solr_admin` will install `search_api_solr` as dependency.)

**Comment by rfay** [comment]
That's it, of course, I skimmed right by it. 

BTW "No existing configset name could be detected on the Solr server for this collection. That is fine if you just create a new collection. Otherwise you should check the logs." should be "No existing configset name could be detected on the Solr server for this collection. That is fine if you are creating a new collection. Otherwise check the logs for errors."
